services:
  quiz-app:
    image: quiz-app:1.0
    build:
      context: backend/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - /home/devops/infra/.env.prod.django