# Generated by Django 5.2.5 on 2025-08-28 08:30

import django.core.validators
import utils.renamePath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quizzes_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_media',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.renamePath.renaming_question_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.renamePath.renaming_question_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
