# Generated by Django 5.2.5 on 2025-09-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_rename_question_questions_question_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_answers',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='student_answers',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quizzes.choices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_answers',
            name='quiz_attempt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizattempt'),
            preserve_default=False,
        ),
    ]
