# Generated by Django 5.2.5 on 2025-08-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom_member',
            old_name='class_id',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='classroom_member',
            old_name='student_id',
            new_name='student',
        ),
    ]
