# Generated by Django 5.2.5 on 2025-08-22 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_rename_class_id_classroom_member_classroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classrooms', through='classrooms.classroom_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
